var entries = new Array(7);
var xday = a.translate("Montag");
entries[0] = new Array("MO", xday);
xday = a.translate("Dienstag");
entries[1] = new Array("TU", xday);
xday = a.translate("Mittwoch");
entries[2] = new Array("WE", xday);
xday = a.translate("Donnerstag");
entries[3] = new Array("TH", xday);
xday = a.translate("Freitag");
entries[4] = new Array("FR", xday);
xday = a.translate("Samstag");
entries[5] = new Array("SA", xday);
xday = a.translate("Sonntag");
entries[6] = new Array("SU", xday);
a.ro(entries);